[package]
name = "riceware"
version = "0.1.0"
edition = "2021"
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.5.4", features = ["derive"] }
eyre = "0.6.12"
lazy_static = "1.4.0"
rand = "0.8.5"
regex = "1.10.4"

[dev-dependencies]
rayon = "1.10.0"
statrs = "0.16.1"
